### ISSUE TITLE
Update INSTALL for cmake, Build Instructions for Bionic

### ISSUE THREAD

**Issue by 4oo4** [swami/swami#17]
I'm attempting to compile this for bionic, and the install reference using GNU make, though it looks like we're using cmake for the build system now. Anyway we can get the build instructions updated for that at some point?

I'm also having an issue with having to compile the libinstpatch library from source (since there isn't an Ubuntu repo for 1.1 that I can find), whereas the cmake config wants a package. I have to go this route since trying to run the 2.0 package for bionic gives me a segfault.

Cheers

**Comment by derselbst** [comment]
Done. Let me know if you are missing something.

**Comment by 4oo4** [comment]
Thanks! The only other thing I think I need I need is the cmake command so that it knows where my locally installed dependencies are, since there are no `libinstpatch` and `fluidsynth` packages I can find that are the right versions for Bionic.

Cheers

**Comment by derselbst** [comment]
> cmake command so that it knows where my locally installed dependencies are

There are no such cmake commands. Cmake uses pkg-config to find all required dependencies automatically. All you have to do is installing libinstpatch and fluidsynth into `/usr` after you've compiled them from source.

You can verify that pkg-config finds them, by executing `pkg-config --list-all`. If pkg-config lists them, cmake will find them as well.

**Comment by 4oo4** [comment]
Perfect, will take a look at that. I wasn't sure if there were any environment arguments for cmake for that, thanks for clarifying.

**Comment by 4oo4** [comment]
`pkg-config` didn't know where things were unless I gave it this environment variable: `PKG_CONFIG_PATH=/usr/local/lib64/pkgconfig`, so when I prepend that to the `make` command, the build works. However, even after building successfully, when trying to launch it, it says it can't find libswamigui.so.1, which is located at `/usr/local/lib` and is a valid symlink. Any suggestions for that?

`swami: error while loading shared libraries: libswamigui.so.1: cannot open shared object file: No such file or directory`

Thanks

**Comment by derselbst** [comment]
Usually, all programs should be installed to `/usr/lib64` (if you are on a 64-bit system). This can be controlled with `-DCMAKE_INSTALL_LIBDIR=/usr/lib64`. Alternatively, add `/usr/local/lib` to `LD_LIBRARY_PATH`.

**Comment by 4oo4** [comment]
Nice, I'm dumb and couldn't remember how to set that in the environment, I'm all good now. Thank you!
