### ISSUE TITLE
Can't detect libinstpatch on Ubuntu Studio 19.04

### ISSUE THREAD

**Issue by ngeiswei** [swami/swami#19]
I've compiled and installed https://github.com/swami/libinstpatch/releases/tag/v1.1.2 but swami does not detect it

```
-- Checking for module 'libinstpatch-1.0>=1.1'
--   No package 'libinstpatch-1.0' found
```

I suspect it has to do with the fact that libinstpatch gets installed under

```
/usr/local/lib64
```

while Ubuntu Studio seems to use

```
/usr/local/lib
```

instead.

Running `sudo ldconfig /usr/local/lib64` or copying the so files under `/usr/local/lib` did not work.

**Comment by ngeiswei** [comment]
Commenting out

https://github.com/swami/libinstpatch/blob/f618c1105303e8b4878eb068129a422e9110a85b/CMakeLists.txt#L46-L54

has fixed the problem :-)

Obviously a better cross-distro fix would be welcome but in the meantime this works.

**Comment by derselbst** [comment]
The `lib` paths under `/usr/local` are usually not included in the search path of pkgconfig by default. That's why it is from my experience better to install software directly to `/usr`. Pls. try:

`cmake -DCMAKE_INSTALL_PREFIX=/usr ..`

which should install libinstpatch to `/usr/lib64`.

**Comment by ngeiswei** [comment]
I don't think it is a problem with the prefix. I tried what you suggest and it does not work either (libinstpatch is not found by swami cmake). Rather it is clear to me it is a problem with the suffix `64` appended after `lib` which for some reason isn't used in Ubuntu Studio.

I suppose you are using a Fedora based distro which uses `lib64` instead of `lib`.

**Comment by derselbst** [comment]
We are using the same suffix logic for Fluidsynth and I'm not aware of any problems there. Unfortunately, I don't see a way to change this without breaking things for somebody else. So ATM, my proposal would be that you either specify the library path explicitly

`cmake -DLIB_INSTALL_DIR=lib`

or that you set the suffix to an empty string

`cmake -DLIB_SUFFIX=""`


(I'm using openSUSE, RPM-based just like Fedora)

---

Another idea would be moving to GNUInstallDirs and see whether it makes any difference. For that, it would be helpful if you could post the console log when you install Swami.

**Comment by ngeiswei** [comment]
I'm having the same problem with Fluidsynth. But using
```
cmake -DLIB_SUFFIX=""
```
works for now. Thanks.
