### ISSUE TITLE
Requested 'libinstpatch-1.0 >= 1.1' but version of libInstPatch is 1.0.0

### ISSUE THREAD

**Issue by OlivierCharton** [swami/swami#45]
Hello,
I'm trying to install swami but somehow I can't get past this error
I tried to install libinstpatch the following ways (sorry my system is in french, if needed I can translate) : 
- sudo apt-get -s install libinstpatch-1.0  => libinstpatch-1.0-0 est déjà la version la plus récente (1.0.0-7); same with libinstpatch-dev
- download the libinstpatch 1.1.4 release and make install it => https://paste.ofcode.org/3adYLj7CiXJfbqMhtZjLbLT 

When I then execute the cmake on swami, I get the error 

> 
> sudo cmake ..
> -- Checking whether system has ANSI C header files
> -- ANSI C header files - found
> -- Checking for module 'libinstpatch-1.0>=1.1'
> --   Requested 'libinstpatch-1.0 >= 1.1' but version of libInstPatch is 1.0.0

What am I doing wrong ?

Also if tried to install swami by apt and got v.2.0.0+svn389-5 , but when I start it I get this : 

> libswami-Message: 22:31:33.554: Loading plugins from /usr/lib/swami
> libswami-Message: 22:31:33.558: Loaded 4 plugins
> Erreur de segmentation
(segmentation error)

Can you help me ? Thanks !

**Comment by OlivierCharton** [comment]
Update :

when I use
swami -p the program starts but I got no sound, and when I then click on plugin/restart I get this message

> (swami:5554): libswami-CRITICAL **: 22:55:35.784: swami_wavetbl_close: assertion 'SWAMI_IS_WAVETBL (wavetbl)' failed
> 
> (swami:5554): libswami-CRITICAL **: 22:55:35.784: swami_wavetbl_open: assertion 'SWAMI_IS_WAVETBL (wavetbl)' failed

I don't know if it helps ?

FI, in my usr/lib/swami/plugins I have the 4 following : 
- fftune.so
- fftune_gui.so
- fluidsynth_gui.so
- fluidsynth_plugin.so

and sudo apt-get install fluidsynth gives me v. 1.1.11-4 but I also manually installed it from release to 2.1.2


final update before waiting for an answer : 
- when I rename both fluidynth.so, swami loads fine (but no sound) without the -p
- when I only remove the fluidsynth_plugin, swami loads, I get the UI with the gain, level etc, but also an error on the prompt 

> (swami:7585): libswami-CRITICAL **: 23:14:44.411: swami_object_find_by_type: assertion 'type != 0' failed

And definitly the fluidsynth_plugin.so makes everything crash if I leave it on

**Comment by derselbst** [comment]
> sudo apt-get -s install libinstpatch-1.0
> Also if tried to install swami by apt and got v.2.0.0+svn389-5

Don't use the packages shipped via apt-get. They are years old and broken. Ubuntu knows about that, but sadly doesn't care: https://bugs.launchpad.net/ubuntu/+source/swami/+bug/1683134

Pls uninstall swami, libinstpatch and fluidsynth, in case you installed any via apt-get.


> download the libinstpatch 1.1.4 release and make install it

That's the correct approach. As you can see, libinstpatch was installed to `/usr/local/lib64`. The default path. Apparently this path is not included in pkg-config's search path. Thus, when building swami from source the new libinstpatch isn't found.

Either update the search path manually via

```bash
export PKG_CONFIG_LIBDIR=/usr/local/lib64/pkgconfig/:$PKG_CONFIG_LIBDIR
```

or (better), specify an install location during cmake, which is suitable for Debian-based systems:

```
cd libinstpatch-1.1.4/build
cmake -DCMAKE_INSTALL_PREFIX=/usr -DLIB_SUFFIX="" ..
make
sudo make install
```

Afterwards, use the same cmake invocation to build and install fluidsynth from source. Then, build the latest swami from source, install it and everything should work fine.
