### ISSUE TITLE
Thanks for the program!

### ISSUE THREAD

**Issue by mrkaban** [swami/swami#52]
Thanks for the program and special thanks for publishing it under the GNU GPL version 2 license!

Added it to the Russian-language site about free software ([link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D0%BC%D1%83%D0%BB%D1%8C%D1%82%D0%B8%D0%BC%D0%B5%D0%B4%D0%B8%D0%B0/%D1%81%D0%B8%D0%BD%D1%82%D0%B5%D0%B7/swami-soundfont.html)).

**Comment by derselbst** [comment]
You're welcome. And thanks for spreading the word :)
