### ISSUE TITLE
need adwaita

### ISSUE THREAD

**Issue by rhwtimetrial** [swami/swami#53]
When running swami 2.0.0 on kubuntu 18.04 the result was:
(swami:3989): Gtk-WARNING **: 11:56:48.207: Unable to locate theme engine in module_path: "adwaita",

(swami:3989): Gtk-WARNING **: 11:56:48.213: Unable to locate theme engine in module_path: "adwaita",
libswami-Message: 11:56:48.221: Loading plugins from /usr/lib/swami
libswami-Message: 11:56:48.229: Loaded 4 plugins
Segmentation fault (core dumped)
Can anyone help?

**Comment by derselbst** [comment]
The version of swami shipped by Ubuntu is years old and broken. Ubuntu knows that, but doesn't care for old distributions, see this bug:

https://bugs.launchpad.net/ubuntu/+source/swami/+bug/1683134

You need to use the latest version 2.2.1, which is currently only shipped on Ubuntu 20.10. Either install that version from a community repository or alternatively compile swami from source by yourself.

**Comment by rhwtimetrial** [comment]
Thanks for your response. I thought I was following the procedure suggested
on the
swami website. I guess I'll try compiling it from source; I believe there
are instructions
for doing that as well.

**Comment by rhwtimetrial** [comment]
Trying to compile from source on  my kubuntu 18.04

For libinstpatch, adding the line:
endif ( ASTYLE )
at the end of CMakeLists.txt seemed to get the ccmake to work okay. At any
rate files were installed in
/usr/local/include/libinstpatch-1.0/libinstpatch

Moving on to swami, not so good. The ccmake error was generated at
CMakeLIsts.txt:125. Evidently the libinstpatch files are not found.
Commentning
out line 125 satisfied ccmake, but then the "make" failed for lack of
finding file(s).

Any help would be appreciated. I'm an old fart who would still be happy
writing 6502 machine code (maybe 6800, too), but i'm in way over my
head in modern software.

**Comment by derselbst** [comment]
Download the latest release tarballs of Swami and libinstpatch here from Github. In each of both unzipped files, do

```
mkdir build && cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr -DLIB_SUFFIX="" ..
make
sudo make install
```

You are not supposed to edit CMakeLists.txt.

**Comment by rhwtimetrial** [comment]
Many thanks. That works like charm. Now I've just got to learn how to use
it!
