### ISSUE TITLE
Thank you very much for the program!

### ISSUE THREAD

**Issue by mrkaban** [swami/swami#58]
Thank you very much for the program released under a free open source license! Added a program to a Russian-language site about free software, here is the [link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D0%BC%D1%83%D0%BB%D1%8C%D1%82%D0%B8%D0%BC%D0%B5%D0%B4%D0%B8%D0%B0/%D1%81%D0%B8%D0%BD%D1%82%D0%B5%D0%B7/swami-soundfont.html).

Please do not abandon the project, this is a very interesting program!

Will the releases be published here?

No more assemblies for Windows?

**Comment by derselbst** [comment]
Thanks for the feedback.

Yes, releases will be published here and eventually announced on swamiproject.org.

Latest prebuilt windows x86 binaries are available for download as build artifact... and may or may not be attached to future stable releases.
https://dev.azure.com/tommbrt/tommbrt/_build/results?buildId=1960&view=results
