### ISSUE TITLE
About critical messages using fluidsynth v 2.0.3 versus v 1.1.6

### ISSUE THREAD

**Issue by jjceresa** [swami/swami#6]
With fluidsynth plugin (fluidsynth v 1.1.6), there is no CRITICAL message in swami's console.

With fluidsynth plugin (fluidsynth v 2.0.3), i got the following messages:

`** (swami.exe:4180): CRITICAL **: Failed to set FluidSynth property 'audio.period-size'`

`** (swami.exe:4180): CRITICAL **: Failed to set FluidSynth property 'audio.periods'`

`(swami.exe:4180): GLib-GObject-WARNING **: value "0,000000" of type `gdouble' is invalid or out of range for property `synth-chorus-speed' of type `gdouble'`

`** (swami.exe:4180): CRITICAL **: Failed to set FluidSynth property 'synth.effects-channels'`

`** (swami.exe:4180): CRITICAL **: Failed to set FluidSynth property 'synth.midi-channels'`

Theses messages are probably due to the changes in fluidsynth 2.0.3 API . Probably  an error in fluidsynth plugin attempting to use fluidsynth API in a wrong way.

**Comment by jjceresa** [comment]
After investigation:

1)CRITICAL messages are due to calling `wavetbl_fluidsynth_set_property() - fluid_settings_setxxxx()` for settings: `audio.period-size, audio.periods,  synth.effects-channels, synth.midi-channels`
On return FLUID_FAILED is returned because in fluidsynth v2.0.3, these settings can't be changed anymore.

2) For `GLib-GObject-WARNING.....` message , i don't know where is the issue.

**Comment by derselbst** [comment]
> On return FLUID_FAILED is returned because in fluidsynth v2.0.3, these settings can't be changed anymore.

You can set and change all settings at any time. There are no restrictions I am aware of. You might check that `wavetbl->settings` is not NULL and that the type of the setting is actually correct.

**Comment by jjceresa** [comment]
>You can set and change all settings at any time. There are no restrictions I am aware of. You might check that wavetbl->settings is not NULL and that the type of the setting is actually correct.

Thanks for confirming.

Please,  did you got following warning message on linux ?:

(swami.exe:4180): GLib-GObject-WARNING **: value "0,000000" of type gdouble' is invalid or out of range for property synth-chorus-speed' of type gdouble'`.

**Comment by derselbst** [comment]
No such warning here.

**Comment by jjceresa** [comment]
>No such warning here.

Ok, thanks.

When deleting `preferences.xml` prior starting swami, such warning does not occur. But when swami is restarted, this warning come back. I need time to investigate further.

Also , I got  `fluidsynth: warning: No preset found on channel 0 [bank=0 prog=0]` on each channel. Please, did you got these warnings also ?

**Comment by derselbst** [comment]
> When deleting preferences.xml prior starting swami, such warning does not occur.

Yes, this file seems to contain all of fluidsynth's settings, some of them however are out of range, which is why setting them fails.

> Please, did you got these warnings also ?

Yes, however only prior to having loaded a soundfont.

**Comment by jjceresa** [comment]
>Yes, this file seems to contain all of fluidsynth's settings,

Yes, preferences.xml contains all settings (i.e swami properties + plugin properties). Theses are loaded when smami is started (in main.c).

>some of them however are out of range, which is why setting them fails.

Ok. Then, when one `quit` swami, swami and plugins's properties are saved to `preferences.xml` file. That means that these preferences should be valid for next swami invocation. However, i got always the same warning mentioned above:
`(swami.exe:4180): GLib-GObject-WARNING **: value "0,000000" of type gdouble' is invalid or out of range for property synth-chorus-speed' of type gdouble'`.` Also, what is a surprise is that no such warning occur on linux.

>Yes, however only prior to having loaded a soundfont.

Thanks for confirming.  

Please note also when sweeping over the piano gui with the mouse cursor, here, new warnings occurs
`fluidsynth: warning: Failed to allocate a synthesis process. (chan=0,key=61)`. (Probably due to polyphony settings being too low).
But when the soundfont is `closed` (unloaded), these warnings still occur. This is not coherent, the piano gui should not continue to ask fluidsynth playing note.

Well, all these warnings seem different issues. I have noticed these.

**Comment by derselbst** [comment]
> fluidsynth: warning: Failed to allocate a synthesis process. (chan=0,key=61).

Same here. This is because synth.polyphony is set to 1. Probably intentionally as one would always only need to play one sample. Not sure if that's a good idea, given that soundfont presets may spawn any number of voices in fluidsynth.

**Comment by jjceresa** [comment]
> Same here.This is because synth.polyphony is set to 1. 

Thanks for confirming. This helps here.

>Probably intentionally as one would always only need to play one sample. 

In fact it should depend what is selected by the user in the left panel of swami gui:
1)At sample level:
- if a sample is selected, the piano gui (or midi driver) should play only this sample (one voice).
- but if multiple sample are selected (i.e 3 at the same time), then 3 voices should be played.

2)At instrument level:
If an instrument is selected, all the samples of this instrument must be played at the same time.
if multiple instruments are selected, all these instruments's sample must be played at the same time.

3)At preset level,should be the same than in (1) (2)

>Not sure if that's a good idea, given that soundfont presets may spawn any number of voices in fluidsynth.

Yes, at any moment swami should be able to give the same and immediate sonic feedback than when these preset will be played later by the musician on its MIDI controller. In fact, a soundfont editor without any soundfont synthesizer's capabilities feedback is a serious handicap.
