### ISSUE TITLE
Cmake configure error

### ISSUE THREAD

**Issue by jjceresa** [swami/swami#67]
We got a cmake configure error since commit  560505d0d3586

1>  -- Checking for module 'libinstpatch-1.0>=1.1.6'
1>  --   Requested 'libinstpatch-1.0 >= 1.1.6' but version of libInstPatch is 1.1.5
1>  CMake Error at C:/Program Files/CMake/share/cmake-3.10/Modules/FindPkgConfig.cmake:415 (message):
1>    A required package was not found.

**Comment by derselbst** [comment]
Pls. update your local libinstpatch copy and try again.

**Comment by jjceresa** [comment]
>Pls. update your local libinstpatch copy and try again.

Done. Thanks.
